### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by xvzontop** [BiscDaBiscuit/BiscDaBiscuit#2]
Ur a little skid who dosen't know shit. Quit programming and go back to scamming kids on the internet

**Comment by BiscDaBiscuit** [comment]
How did I skid

Sent from my iPhone

On Jun 10, 2022, at 6:36 AM, xvz ***@***.***> wrote:

﻿

Ur a little skid who dosen't know shit. Quit programming and go back to scamming kids on the internet

**Comment by xvzontop** [comment]
lol im kidding
